### PR TITLE
MutationObserver - fix for dynamic content update

### PR DESCRIPTION
**Pull request by dobrysmak**
Added dynamic content change event. On DOM content change, using HTML5 Mutation Observer, ngTinyScrollbar fires the update method for scrollbar recalculation 

Works with IE11+, FF, Chrome, Opera, Safari
http://caniuse.com/#feat=mutationobserver

Hope that helps :)

### CODE REVIEW

**Comment by mod3st** [comment]
Is there any possibility to use mutation observers optionally?
IE9 won't be supported but it is still better solution than not supporting observers at all.

**Comment by yads** [comment]
Yeah that's a good idea.

**Comment by yads** [comment]
Merged into 0.8.0. See new README for support.

**Comment by mod3st** [comment]
Thank you!

2015-05-07 16:50 GMT+02:00 Vadim Kazakov <notifications@github.com>:

**Pull request closed without merging**
