### PR TITLE
fix: $diggest is digest is already in progress

### PR DESCRIPTION
**Pull request by brujo696**
when I apply a resize manually, like #2 , I have this problem, fix with this code

### CODE REVIEW

**Comment by yads** [comment]
Hmm, I'm not sure I had this issue, can you post the code that was resulting in needing to fix this?

**Comment by Aaron-Pool** [comment]
I've also had this problem, and using $timeout was the solution.

**Comment by Igmat** [comment]
I have this problem too. And it was fixed in my case just by commenting call of `$digest`. Actually I don't really understand why it should be there?

**Comment by yads** [comment]
@Igmat I think you might be right, the `$digest` is likely unnecessary.

**Comment by Igmat** [comment]
@yads so can we help somehow? By providing test cases or adding PR with unit test, anything else?
It's just a little bit annoying that we should keep fixed version of this lightweight library in VCS instead of using only bower file.

**Comment by yads** [comment]
Pushed fix as 0.9.2

**Pull request closed without merging**
